---
title: "Exercise B"
author: "Mitchell Toomey"
date: February 4, 2021
output: html_notebook
---

```{r}
library(here)
```

### 1

```{r}
# Created a vector that contains 100 random values from a normal distr. with a mean of 50 and an SD of 10.

vector_a <- 1:100

vector_a <- rnorm(100, 50, 10)

```

### 2

```{r}
# I selected the 1st, 3rd, and 8th elements of the vector.

vector_b <- vector_a[c(1, 3, 8)]
```

### 3

```{r}
# I created a vector with all elements of vector a except the 10th and 15th element

vector_c <- vector_a[c(-10, -15)]
```

### 4

```{r}
# I created a vector with all elements of vector a less than 40. 

vector_d <- vector_a[vector_a < 40] 
```

### 5

```{r}
length(vector_d)
```

### 6

All 100 elements of vector_a are positive.

```{r}
length(vector_a > 0)
```

### 7

The minimum value of vector_a is 24.19 and the maximum value is 75.65.

```{r}
range(vector_a)
```

### 8

```{r}
vector_e <- sort(vector_a)
```

### 9

```{r}
vector_f <- seq(2, 100, by = 2)
```

### 10

```{r}
vector_g <- rev(vector_f)
```

### 11

```{r}
vector_h <- c(vector_f, vector_g)
```

### 12

```{r}
# I created three different matrices.

matrix_a <- matrix(c(4, 2, 6, 2, 3, 6),
                    nrow = 3,
                    ncol = 2)

matrix_b <- matrix(c(7, 2, 3, 5),
                    nrow = 2,
                    ncol = 2)

matrix_c <- matrix(c(8, 1, 1, 5, 3, 7, 1, 4, 2),
                    nrow = 3,
                    ncol = 3)
```

### 13

The value in the first row, second column of matrix_a is 2.

```{r}
# I extracted data from the first row and second column of matrix a and stored it in my value. 

my_value <- matrix_a[1,2]

my_value
```

### 14

```{r}
#I created a new matrix with the bottom two rows of matrix a.

matrix_d <- matrix_a[-1,]
```

### 15

```{r}
colnames(matrix_a) <- c("var_1", "var_2")
```

### 16

```{r}
rownames(matrix_a) <- c("Bob", "Mary", "Shameeka")
```

### 17

```{r}
# I transposed matrix c and stored the results in matrix e.

matrix_e <- t(matrix_c)
```

### 18

```{r}
matrix_e <- matrix_e + 5
```

### 19

```{r}
hsb2 <- read.csv(here("Data", "hsb2.csv"))

hsb2_matrix <- matrix(c(hsb2$read, hsb2$write, hsb2$math, hsb2$science, hsb2$socst),
                    ncol = 5)

colnames(hsb2_matrix) <- c("read", "write", "math", "science", "socst")
```

### 20

```{r}
# I transposed the hsb2_matrix I created in step 19. 

hsb2_trans <- t(hsb2_matrix)
```

### 21

```{r}
# I calculated the means of each of the rows in hsb2_trans. They are in the 
# following order: read, write, math, science, socst. 

test_means <- rowMeans(hsb2_trans)
```

### 22

```{r}
public <- subset(hsb2, hsb2$schtyp == 1)

private <- subset(hsb2, hsb2$schtyp == 2)

public_scores <- matrix(c(public$read,                            
                          public$write,                            
                          public$math,                            
                          public$science,                            
                          public$socst),                        
                          nrow = 200,                       
                          ncol = 5)

private_scores <- matrix(c(private$read,                             
                           private$write,                            
                           private$math,                            
                           private$science,                         
                           private$socst),                        
                           nrow = 200,                         
                           ncol = 5)
```

### 23 

```{r}
public_scores <- public_scores[1:25, ]

private_scores <- private_scores[1:25, ]

scores_array <- array(c(public_scores, private_scores),                     
                      dim = c(25, 5, 2))
```

### 24

```{r}
dimnames(scores_array) = list(c(NULL),                         
                              c("Read", "Write", "Math", "Science", "SocStud"),
                              c("Public School", "Private School"))
```

### 25

```{r}
# Created a new factor. 

student_class <- factor(c(1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 
                            4, 4, 4))

levels(student_class) <- c("freshman", "sophomore", "junior", "senior")
```

### 26

```{r}
levels(student_class) <- c("1st year", "2nd year", "3rd year", "4th year")
```

### 27

```{r}
# excluded 1st year students from the factor.

new_student_class <- student_class[student_class != "1st year"]
```

### 28

```{r}
# dropped the unused level from the factor.

new_student_class <- droplevels(new_student_class)
```

### 29

```{r}
hsb2 <- read.csv(here("Data", "hsb2.csv"))

hsb2$female <- factor(hsb2$female,
                           levels = c(0, 1),
                           labels = c("male", "female"),
                           ordered = FALSE)

hsb2$race <- factor(hsb2$race,
                           levels = c(1, 2, 3, 4),
                           labels = c("Hispanic", "Asian", "African American",
                                      "White"),
                           ordered = FALSE)

hsb2$ses <- factor(hsb2$ses,
                           levels = c(1, 2, 3),
                           labels = c("low", "middle", "high"),
                           ordered = TRUE)

hsb2$schtyp <- factor(hsb2$schtyp,
                           levels = c(1, 2),
                           labels = c("public", "private"),
                           ordered = FALSE)

hsb2$prog <- factor(hsb2$prog,
                           levels = c(1, 2, 3),
                           labels = c("general", "academic", "vocational"),
                           ordered = FALSE)
```

### 30

```{r}
tapply(hsb2$science, hsb2$female, mean)

tapply(hsb2$science, hsb2$ses, mean)

tapply(hsb2$science, (list(hsb2$female, hsb2$ses)), mean)
```

### 31

```{r}
student_math_quartile <- hsb2$math

quantile(student_math_quartile)
```

### 32

```{r}
sorted_math_score <- sort(student_math_quartile)
```

### 33

```{r}
# randomly selected 1000 scores from a normal distr. with a mean of 100 and SD of 15. 

rand_norms <- rnorm(1000, 100, 15)
```

### 34

```{r}
# use the cut function to organize data into four bins

rand_norms_new <- cut(rand_norms,
                      breaks = c(0, 80, 100, 120))

levels(rand_norms_new) <- c ("First Bin", "Second Bin", "Third Bin", "Fourth Bin")

```

### 35

```{r}
table(rand_norms_new)

prop.table(table(rand_norms_new))
```
