---
title: "R Notebook"
output: html_notebook
---

```{r}
library(here)
```

### 1

```{r}

# creating a list

my_courses <- list(c("EDRM 718", "EDEX 809", "EDCE 825"),
                   c("Dr. Seaman, Dr. Wolfe", "Dr. Gold"),
                   c(3, 3, 3))

```

### 2

```{r}

hsb2 <- read.csv(here("Data", "hsb2.csv"))

ses_low <- subset(hsb2, hsb2$ses == 1)

ses_middle <- subset(hsb2, hsb2$ses == 2)

ses_high <- subset(hsb2, hsb2$ses == 3)

ses_scores_low <- matrix(c(ses_low$read,                            
                          ses_low$write,                            
                          ses_low$math,                            
                          ses_low$science,                            
                          ses_low$socst),                        
                          nrow = nrow(ses_low),                       
                          ncol = 5)

ses_scores_middle <- matrix(c(ses_middle$read,                            
                          ses_middle$write,                            
                          ses_middle$math,                            
                          ses_middle$science,                            
                          ses_middle$socst),                        
                          nrow = nrow(ses_middle),                       
                          ncol = 5)

ses_scores_high <- matrix(c(ses_high$read,                            
                          ses_high$write,                            
                          ses_high$math,                            
                          ses_high$science,                            
                          ses_high$socst),                        
                          nrow = nrow(ses_high),                       
                          ncol = 5)

ses_scores_list <- list(ses_scores_low, 
                        ses_scores_middle, 
                        ses_scores_high)


names(ses_scores_list) <- c("SES_low",
                            "SES_middle",
                            "SES_high")

# plot and correlation for Low SES

plot(x = ses_scores_list$SES_low[ , 1],
     y = ses_scores_list$SES_low[ , 3],
     main = paste("Plot of Reading score to Math Score for ",
                  names(ses_scores_list[1])),
     xlab = "Reading Scores",
     ylab = "Math Sores")

cor(x = ses_scores_list$SES_low[ , 1],
    y = ses_scores_list$SES_low[ , 3])

# plot and correlation for Middle SES

plot(x = ses_scores_list$SES_middle[ , 1],
     y = ses_scores_list$SES_middle[ , 3],
     main = paste("Plot of Reading score to Math Score for ",
                  names(ses_scores_list[2])),
     xlab = "Reading Scores",
     ylab = "Math Sores")

cor(x = ses_scores_list$SES_middle[ , 1],
    y = ses_scores_list$SES_middle[ , 3])

# Plot and correlation for high SES

plot(x = ses_scores_list$SES_high[ , 1],
     y = ses_scores_list$SES_high[ , 3],
     main = paste("Plot of Reading score to Math Score for ",
                  names(ses_scores_list[3])),
     xlab = "Reading Scores",
     ylab = "Math Sores")

cor(x = ses_scores_list$SES_high[ , 1],
    y = ses_scores_list$SES_high[ , 3])

```

### 3

```{r}
class_list <- list("Ali Alzughaibi", "Asiye Demir", "Bryan Terlizzi",
                   "Cade Abrams", "Dana Sox", "Erin Wilson", "Geophrey Odero",
                   "Hazza Bin-Hazza", "Hui Jiang", "Julie Wang",
                   "Michael Seidman", "Mohammed Quasem", "Olivia Lewis",
                   "Robyn Pernetti", "Ryan Dastrup", "Shelby Gonzales",
                   "Talal Alshehri", "Charles Walters")

sample(class_list, 3)

learning_group <- data.frame("ID" = 1:4,
                      "First Name" = c("Hazza", "Olivia", "Cade", "Mitchell"),
                      "Last Name" = c("Bin-Hazza", "Lewis", "Abrams", "Toomey"),
                      "Email" = c("binhazza@email.sc.edu", "ojlewis@email.sc.edu",
                                  "tcabrams@email.sc.edu", "tt12@email.sc.edu"),
                      "Program of Study" = c("Language and Literacy", "Counselor Education",
                                             "Physical Education", "Counselor Education"),
                      "Years in Program" = c("2", "2", "2",
                                             "2"))

full_name <- paste(learning_group$First.Name, learning_group$Last.Name, sep = ",")

learning_group <- cbind(learning_group, full_name)

learning_group_new <- learning_group[, c(1, 2, 3, 7, 4, 5, 6)]

# Creating a logical variable if the learning group members are in their programs
# for more than two years.

learning_group_new$more.than.two.years <- learning_group_new$Years.in.Program >3
```

### no longer assigned for this week

```{r}

# a. load the mount juniper data and put it in a data fram

mount_juniper_data <- read.csv(here("Data","Mount Juniper Elementary Data.csv"))

data.frame(mount_juniper_data)

# b. check the score column to determine if there are missing data

anyNA(mount_juniper_data$Score)

# c. prints either "there are no missing data" or "there are missing data", 
# depending on which is true

# I created a vector to indicate any missing values, and if there were, told
# it to display "there are missing data"

mount_juniper_missing <- anyNA(mount_juniper_data$Score)

mount_juniper_missing <- ifelse(mount_juniper_missing == TRUE, 
                                "There are missing data")

print(mount_juniper_missing)

```

### 4

```{r}

# Remove missing data
mount_juniper_data <- na.omit(mount_juniper_data)

# Coerce grade to factor
juniper_grade <- factor(mount_juniper_data$Grade,
                        levels = c(3, 4, 5),
                        labels = c("Grade 3", "Grade 4", "Grade 5"),
                        ordered = FALSE)

anova_grade <- aov(mount_juniper_data$Score ~ juniper_grade, 
                      data = mount_juniper_data)

summary(anova_grade)

# Not sure if my "anova grade" object and summary function fulfill the 
# first part for problem 6 too

```

### no longer assigned for this week

```{r}

# Store ANOVA in a separate object with the p-value extracted

anova_results <- summary(anova_grade)[[1]][[1,5]]

# not sure what the first 1 is, but the second 1,5 represents where the p-value
# is located in the anova table

# telling R to print not statistically significant if the p-value is > .05

anova_results <- ifelse(anova_results > .05, 
                                "Not statistically significant")

print(anova_results)
```

### no longer assigned for this week

```{r}

# Adding a "results" attribute to the anova grade object

# I am using anova_grade as the object. I am not sure why exactly I use this
# and not the anova_results object-- but the latter shows attributes as NULL.
# I think because the anova_results object only has the sign. level in it.

attributes(anova_grade)$Results<- ifelse(anova_results > .05, 
                                "Not statistically significant")

```

### no longer assigned for this week

```{r}

# Consider a population of normally distributed scores with a mean of 100 and a standard deviation of15. Write a script to draw 1,000 random samples, each of size 40, from this population.

norm_pop <- replicate(1000, sample(rnorm(1000, 100, 15), size = 40))

# Calculate and store each mean in a vector of means

norm_pop_means <- mean(norm_pop)

# Calculate the mean of the sample means

mean_of_means <- mean(norm_pop_means)

# Determine the difference between the true mean of 100 and the mean of the 
# sample means

mean_of_means - 100

# meaning there is no real difference between the true mean and the sample mean

```

### 5

```{r}

# subset the scores from the total hsb2

hsb2_scores <- subset(hsb2 [, 7:11])

# a. stored the sd's of each score in a list

hsb2_sd_list <- lapply(hsb2_scores, sd) 

# b. 

hsb2_sd_vector <- sapply(hsb2_scores, sd)

# c.

hsb2_scores$sd <- apply(hsb2_scores, MARGIN = 1, sd)

# d. calculated sd's of each score by school type individually

hsb2_read_schtyp <- tapply(hsb2_scores$read, hsb2$schtyp, sd)

hsb2_write_schtyp <- tapply(hsb2$write, hsb2$schtyp, sd)

hsb2_math_schtyp <- tapply(hsb2$math, hsb2$schtyp, sd)

hsb2_science_schtyp <- tapply(hsb2$science, hsb2$schtyp, sd)

hsb2_socst_schtyp <- tapply(hsb2$socst, hsb2$schtyp, sd)

# I then column binded each of the sd's by school type

hsb2_schtyp_score <- cbind(hsb2_read_schtyp, hsb2_write_schtyp, 
                           hsb2_math_schtyp,
                           hsb2_science_schtyp, hsb2_socst_schtyp)

# then I transposed it to make it look prettier

hsb2_schtyp_score <- t(hsb2_schtyp_score)

```

### 6

```{r}

# construct a vector of 9 different numbers between 0 and 100

rand_nums <- sample(0:100, 9)

# add two missing indicators to the vector

rand_nums <- sample(append(rand_nums, NA))
rand_nums <- sample(append(rand_nums, NA))


# add infinity to the vector

rand_nums <- sample(append(rand_nums, Inf))

# Range function

# find range and omit missing data

range(rand_nums, na.rm = TRUE)

# find range, omit random numbers, omit infinity

range(rand_nums, na.rm = TRUE, finite = TRUE)

# trimming random numbers

x <- rnorm(100)
range(x, trim = .10)

z <- rnorm(3, 5, 20)
range(z, robust = TRUE)

#use character objects

food <- (c("hamburger", "salad", "pizza", "french fries"))
range(food)

```
